

# This file was *autogenerated* from the file solve.sage
from sage.all_cmdline import *   # import sage library

_sage_const_41 = Integer(41); _sage_const_27 = Integer(27); _sage_const_64 = Integer(64); _sage_const_37 = Integer(37)
from curses.ascii import islower


FLAG  = open('message.txt').read()
output = ''
for i in FLAG.split():
    inv = inverse_mod(int(i), _sage_const_41 )
    print (str(int(i) * int(inv) %_sage_const_41 )) 
    if inv < _sage_const_27 :
        output += chr(inv + _sage_const_64 )
    elif inv < _sage_const_37 :
        output += str(inv - _sage_const_27 )
    elif inv == _sage_const_37 :
        output += '_'
        
print(output)

